package twin.spring.unit;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Lombok @Slf4j annotation.
 * 
 * @see <a href="https://projectlombok.org/features/Log">Lombok @Slf4j</a>
 */
@DisplayName("Lombok @Slf4j Annotation Tests")
class LombokSlf4jAnnotationTest {

    /**
     * Test service class with @Slf4j annotation.
     */
    @Slf4j
    static class TestService {
        public String process(String input) {
            if (log.isDebugEnabled()) {
                log.debug("Processing input: {}", input);
            }
            return "processed: " + input;
        }
    }

    @Test
    @DisplayName("Should have log field generated by @Slf4j")
    void shouldHaveLogField() throws Exception {
        // Test that the log field exists
        Field logField = TestService.class.getDeclaredField("log");
        assertNotNull(logField);
        
        // Verify the field type is org.slf4j.Logger
        assertEquals("org.slf4j.Logger", logField.getType().getName());
    }

    @Test
    @DisplayName("Should be able to use log field for logging")
    void shouldBeAbleToUseLogField() {
        TestService service = new TestService();
        
        // This should not throw any exception
        assertDoesNotThrow(() -> {
            service.process("test input");
        });
    }

    @Test
    @DisplayName("Log field should be accessible")
    void logFieldShouldBeAccessible() throws Exception {
        TestService service = new TestService();
        Field logField = TestService.class.getDeclaredField("log");
        logField.setAccessible(true);
        
        Object logObject = logField.get(service);
        assertNotNull(logObject);
        assertTrue(logObject instanceof org.slf4j.Logger);
    }
}